# Generated by Django 3.2.5 on 2021-07-10 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='app_store',
            new_name='app_name',
        ),
        migrations.RemoveField(
            model_name='app',
            name='google_play',
        ),
    ]
