# Generated by Django 3.2.5 on 2021-07-10 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
