# Generated by Django 3.2.5 on 2021-07-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GooglePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='apps',
        ),
        migrations.DeleteModel(
            name='App',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='app_store_apps',
            field=models.ManyToManyField(related_name='subscriber', to='subscribe.AppStore'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='google_play_apps',
            field=models.ManyToManyField(related_name='subscriber', to='subscribe.GooglePlay'),
        ),
    ]
