# Generated by Django 3.2.5 on 2021-07-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_auto_20210714_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appstore',
            old_name='app_name',
            new_name='app_id',
        ),
        migrations.RenameField(
            model_name='googleplay',
            old_name='app_name',
            new_name='app_id',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='app_store_apps',
            new_name='apple_app_id',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='google_play_apps',
            new_name='google_app_id',
        ),
    ]
