# Generated by Django 3.2.5 on 2021-07-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_auto_20210714_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstore',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appstore',
            name='developer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='googleplay',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='googleplay',
            name='developer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
