# Generated by Django 3.2.5 on 2021-07-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0007_auto_20210715_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='apple_app_id',
            new_name='app_store',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='google_app_id',
            new_name='google_play',
        ),
    ]
