# Generated by Django 3.2.5 on 2021-07-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0008_auto_20210722_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
