# Generated by Django 3.2.5 on 2021-07-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0011_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstore',
            name='app_icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='googleplay',
            name='app_icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
