# Generated by Django 3.2.5 on 2021-08-01 12:06

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0012_auto_20210730_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
