# Generated by Django 3.2.5 on 2021-08-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0013_subscriber_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='country',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('app_store', models.ManyToManyField(related_name='countries', to='subscribe.AppStore')),
                ('google_play', models.ManyToManyField(related_name='countries', to='subscribe.GooglePlay')),
            ],
        ),
    ]
