# Generated by Django 3.2.5 on 2021-08-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0014_auto_20210801_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='country',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='country',
            field=models.ManyToManyField(related_name='subscriber', to='subscribe.Country'),
        ),
    ]
