# Generated by Django 3.2.5 on 2021-08-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0015_auto_20210801_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_name',
            field=models.CharField(default='INDIA', max_length=50),
            preserve_default=False,
        ),
    ]
