from django.shortcuts import render, reverse
from django.views.generic import FormView, ListView, TemplateView
from .forms import AppStoreForm, GooglePlayForm, SubscribeForm
import play_scraper
from .models import GooglePlay, Subscriber, AppStore
from itunes_app_scraper.scraper import AppStoreScraper
from pprint import pprint
from django.conf import settings
# Create your views here.

class HomePageView(TemplateView):
    template_name = "subscribe/home.html"


class GooglePlayFormView(FormView):
    template_name = "subscribe/google_play.html"
    form_class = GooglePlayForm

    def get_success_url(self):
        return reverse('subscribe:google-app-list', args=[self.kwargs.get('app_name')])

    def form_valid(self, form):
        app_name = form.cleaned_data['app_name']
        self.kwargs.update(
            {
                'app_name': app_name
            }
        )
        print("KWARGS:", self.kwargs)
        return super(GooglePlayFormView, self).form_valid(form)


class GooglePlayAppListView(TemplateView):
    template_name = "subscribe/app_list.html"

    def get_context_data(self, **kwargs):
        context = super(GooglePlayAppListView, self).get_context_data(**kwargs)
        app_name = self.kwargs.get('app_name')
        apps = play_scraper.search(app_name, page=1, gl=settings.DEFAULT_COUNTRY)
        context.update({
            'apps': apps
        })
        return context


class GoogleSubscribeFormView(FormView):
    template_name = "subscribe/subscribe.html"
    form_class = SubscribeForm
    success_url = '/'
    print('fjoifefoehjf')

    def form_valid(self, form):
        app_id = self.kwargs['app_id']
        from google_play_scraper import app
        details = app(
            app_id,
            lang='en',
            country='in'
        )
        pprint(details)
        app_name = details['title']
        developer_id = details['developerId']
        email = form.cleaned_data['email']
        sub, sub_created = Subscriber.objects.get_or_create(email=email)
        app, app_created = GooglePlay.objects.get_or_create(app_id=app_id,
                                                            app_name=app_name,
                                                            developer_id=developer_id)
        # if sub_created or app_created:
        #     form.send_mail(email, app_id)
        sub.google_app_id.add(app)
        sub.save()
        return super(GoogleSubscribeFormView, self).form_valid(form)


class AppStoreFormView(FormView):
    form_class = AppStoreForm
    template_name = "subscribe/app_store.html"

    def get_success_url(self):
        return reverse('subscribe:app-store-app-list', args=[self.kwargs.get('app_name')])

    def form_valid(self, form):
        app_name = form.cleaned_data['app_name']
        self.kwargs.update(
            {
                'app_name': app_name
            }
        )
        print("KWARGS:", self.kwargs)
        return super(AppStoreFormView, self).form_valid(form)


class AppStoreAppListView(TemplateView):
    template_name = "subscribe/app_store_list.html"

    def get_context_data(self, **kwargs):
        context = super(AppStoreAppListView, self).get_context_data(**kwargs)
        app_name = self.kwargs.get('app_name')
        scraper = AppStoreScraper()
        results = scraper.get_app_ids_for_query(app_name, country="in")
        if len(results) > 6:
            results = results[:6]
        apps = []
        for i in results:
            apps.append(scraper.get_app_details(app_id=i, country="in"))
        context.update({
            'apps': apps
        })
        return context

'http://itunes.apple.com/rss/customerreviews/page=1/id=389801252/app/sortby=mostrecent/json?cc=in';

class AppStoreSubscribeForm(FormView):
    template_name = "subscribe/subscribe.html"
    form_class = SubscribeForm
    success_url = '/'

    def form_valid(self, form):
        app_id = self.kwargs['app_id']
        email = form.cleaned_data['email']
        scraper = AppStoreScraper()
        details = scraper.get_app_details(app_id=app_id, country="in")
        app_name = details['trackName']
        devloper_id = details['artistId']
        sub, sub_created = Subscriber.objects.get_or_create(email=email)
        print("APP:", AppStore)
        app, app_created = AppStore.objects.get_or_create(app_id=app_id,
                                                          app_name=app_name,
                                                          developer_id=devloper_id)
        # if sub_created or app_created:
        #     form.send_mail(email, app_id)
        sub.apple_app_id.add(app)
        sub.save()
        return super(AppStoreSubscribeForm, self).form_valid(form)

x = {"feed":{"author":{"name":{"label":"iTunes Store"}, "uri":{"label":"http://www.apple.com/itunes/"}}, "entry":[
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1198781359"}, "name":{"label":"per7cs"}, "label":""}, "updated":{"label":"2021-07-14T01:07:33-07:00"}, "im:rating":{"label":"4"}, "im:version":{"label":"196.0"}, "id":{"label":"7574662303"}, "title":{"label":":/"}, "content":{"label":"bruh . It don’t let me see my pronouns", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id606775397"}, "name":{"label":"vangelisMaria"}, "label":""}, "updated":{"label":"2021-07-14T00:58:49-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7574640599"}, "title":{"label":"Love it"}, "content":{"label":"I love it", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id8549099"}, "name":{"label":"JoeOfAllTrades"}, "label":""}, "updated":{"label":"2021-07-14T00:08:31-07:00"}, "im:rating":{"label":"3"}, "im:version":{"label":"196.0"}, "id":{"label":"7574514336"}, "title":{"label":"Censorship"}, "content":{"label":"IG has done a pretty bad job of weeding out fake news from humor and satire. I’ve had multiple posts blocked and then reinstated. Now they’ve made it next to impossible to dispute blocked posts.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id984217913"}, "name":{"label":"chkkbyj"}, "label":""}, "updated":{"label":"2021-07-13T23:38:28-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7574437816"}, "title":{"label":"Ig"}, "content":{"label":"I love sharing my armature photos and just silly things. Easy to use and plenty to see. Thanks ig", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1288065841"}, "name":{"label":"renlol2"}, "label":""}, "updated":{"label":"2021-07-13T23:37:26-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7574435220"}, "title":{"label":"Gave out person info"}, "content":{"label":"I’ve had multiple issues with Instagram. First off they always suspend my account and say I “shared it” with someone else and I’ve done nothing of the sort. (They do this and fix it 2 times a week since I got insta) AND THEN my boyfriend was looking at my account and there was a thing that said email or text which I NEVER said put my personal info out and yet Instagram did.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1208154940"}, "name":{"label":"305 215"}, "label":""}, "updated":{"label":"2021-07-13T22:59:16-07:00"}, "im:rating":{"label":"3"}, "im:version":{"label":"196.0"}, "id":{"label":"7574344518"}, "title":{"label":"To Instagram"}, "content":{"label":"Can y’all stop allowing these fake pages to view my story or even go on my DMs I am tired of seeing it and also can y’all decrease the time there’s no way i was on Instagram for 4 hours i was only on it for About 2-6 minutes maybe even 15 minutes", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id461175836"}, "name":{"label":"shady0327"}, "label":""}, "updated":{"label":"2021-07-13T22:52:39-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7574328542"}, "title":{"label":"Censorship"}, "content":{"label":"Stop censorship on antiChina content", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id34514161"}, "name":{"label":"celicaboi48"}, "label":""}, "updated":{"label":"2021-07-13T22:36:13-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7574288654"}, "title":{"label":"Love Instagram... Can't use it..."}, "content":{"label":"I use Instagram daily, both for pleasure and for work. But over the last 6 months it's become literally unusable. For a few months, it locked me out of my account on almost a daily basis, asking me to reset my password. I complied and kept using the app (quite normally mind you, liking around 20-50 pics a day, sending a few dms, and adding maybe 2-10 new accounts a day). \nI believe they tried to fix the problem recently by adding in a face recognition captcha which was way easier and pretty helpful. \nBut then the dreaded restriction 49 error started. Literally daily. I can't use the app. I'm \"shadowbanned\" I believe? I use the app normally, no spamming and nothing out of the ordinary. I didn't get hacked. I have no 3rd party apps. I made my account private. I uninstalled and reinstalled. I changed my password multiple times. Nothing works. I get blocked daily. I use the app for a couple of hours after I'm unblocked, and poof: restriction 49. I don't understand an app that punishes you for using it lol. \nCan anyone help? There is no way to contact Instagram and the error notifications do nothing. This app is now garbage.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id748647934"}, "name":{"label":"Older version of chrome"}, "label":""}, "updated":{"label":"2021-07-13T22:31:05-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7574276321"}, "title":{"label":"Suspended account"}, "content":{"label":"This past week my Instagram account is repeatedly being suspended and it isn’t a week long suspension and is 24 hrs and then the 30 maybe 40 minutes after I start using I get a suspended \nI never post anything wrong…all I do is just see people Instagram stories from those I follow", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id300086931"}, "name":{"label":"Cole da king"}, "label":""}, "updated":{"label":"2021-07-13T22:29:55-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7574273429"}, "title":{"label":"cant stand the experimental shop and reel feature"}, "content":{"label":"at the bare minimum, there should be a way to revert back to the original", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id108001009"}, "name":{"label":"tmatthews14"}, "label":""}, "updated":{"label":"2021-07-13T22:15:39-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7574238980"}, "title":{"label":"No iPad App?"}, "content":{"label":"At this point your just lazy.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id247831033"}, "name":{"label":"🔥👎🏾"}, "label":""}, "updated":{"label":"2021-07-13T22:14:41-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7574236489"}, "title":{"label":"Can’t see any INSIGHTS!!!!!!  ..... NO COMMENT !!!!!!"}, "content":{"label":"Can u tell me why we can not see on our business acc any INSIGHTS????\nOh ... I forget u can’t ......\nTERRIBLE APP!!!!!", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1072512550"}, "name":{"label":"malaina6"}, "label":""}, "updated":{"label":"2021-07-13T22:12:44-07:00"}, "im:rating":{"label":"3"}, "im:version":{"label":"196.0"}, "id":{"label":"7574231664"}, "title":{"label":"delete one picture from a post"}, "content":{"label":"Can you make it so the you can edit one picture out so I don’t have to delete an old post when I just wanna delete 1-2 picture out of it", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1305545769"}, "name":{"label":"candice😅"}, "label":""}, "updated":{"label":"2021-07-13T22:02:31-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7574206594"}, "title":{"label":"Fr"}, "content":{"label":"Dfggvff", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id122114453"}, "name":{"label":"Goodell D"}, "label":""}, "updated":{"label":"2021-07-13T21:42:32-07:00"}, "im:rating":{"label":"2"}, "im:version":{"label":"196.0"}, "id":{"label":"7574156965"}, "title":{"label":"Main Photo Feed"}, "content":{"label":"Please return the main photo feed.  I’m not the type to do videos, but I love showing my portraits and getting feedback!", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1197905231"}, "name":{"label":"sapan othi"}, "label":""}, "updated":{"label":"2021-07-13T21:39:11-07:00"}, "im:rating":{"label":"4"}, "im:version":{"label":"196.0"}, "id":{"label":"7574148359"}, "title":{"label":"Follower and likes"}, "content":{"label":"My reels not a viral and no likes and views on my reels so please increase my like , view on reels and increase my followers..", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1249111152"}, "name":{"label":"tbking831"}, "label":""}, "updated":{"label":"2021-07-13T21:37:23-07:00"}, "im:rating":{"label":"3"}, "im:version":{"label":"196.0"}, "id":{"label":"7574143968"}, "title":{"label":"Bug with putting music on my story"}, "content":{"label":"Whenever I choose a song to play on my story, Instagram refuses to load the song, therefor disallowing me to choose which time in the song to start playing from. Only when I post the song onto my story, instagram loads it and then will either play it from a predetermined time, or from 0:00. Please fix this.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1090480669"}, "name":{"label":"primo tha king"}, "label":""}, "updated":{"label":"2021-07-13T21:17:22-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7574092462"}, "title":{"label":"Instagram"}, "content":{"label":"The best social platform", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id599838425"}, "name":{"label":"jammy12:"}, "label":""}, "updated":{"label":"2021-07-13T21:12:39-07:00"}, "im:rating":{"label":"2"}, "im:version":{"label":"196.0"}, "id":{"label":"7574080366"}, "title":{"label":"Hey fix my problem i am unable to see any messages. After updating instagram"}, "content":{"label":"After updating my Instagram  i get  messages notifications but unable to see from 2 days i see only loading screen", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id241992397"}, "name":{"label":"JGOSA"}, "label":""}, "updated":{"label":"2021-07-13T21:07:08-07:00"}, "im:rating":{"label":"2"}, "im:version":{"label":"196.0"}, "id":{"label":"7574066250"}, "title":{"label":"I like it"}, "content":{"label":"I’ve updated the app and still can’t remix reels. I’ve sent the issue to Instagram and still no word on how to fix this on my end", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id955247520"}, "name":{"label":"tiffy_is_fangirling"}, "label":""}, "updated":{"label":"2021-07-13T20:58:48-07:00"}, "im:rating":{"label":"2"}, "im:version":{"label":"196.0"}, "id":{"label":"7574044370"}, "title":{"label":"Stop the new updates they are confusing and useless"}, "content":{"label":"Instagram is messing up real bad, what with going to share a post in your story and having to go to stickers and press RESHARE which takes even LONGER TO SHARE and because it's confusing and a long process it's not even a quick share anymore and it makes you not even share it anymore.  Stop trying to be trendy, go back a few updates it's WAYYY better. Y'all keep going like this the ratings are gonna go under.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1142669918"}, "name":{"label":"Vxaleria_"}, "label":""}, "updated":{"label":"2021-07-13T20:58:31-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7574043640"}, "title":{"label":"photo booth filter"}, "content":{"label":"my friend kristel is mad at you for removing the photo booth feature add it back or else☺️", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id690414928"}, "name":{"label":"james ig"}, "label":""}, "updated":{"label":"2021-07-13T20:54:01-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7574031459"}, "title":{"label":"Yea"}, "content":{"label":"It’s cool ig and fun", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id217361703"}, "name":{"label":"SpicyEquation"}, "label":""}, "updated":{"label":"2021-07-13T20:44:04-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7574005098"}, "title":{"label":"Can’t stare posts to story"}, "content":{"label":"I hate that I can’t even share posts to my story anymore without having to go through hoops of making my OWN story with a “reshare” option. I loved that I was able to bring awareness about specific events happening, promoting artists/friends or just sharing memes that I think are hilarious with a simple click of a button. Now I don’t really want to use the app because I can’t even share what I’d like to share on my OWN social media page.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1177032805"}, "name":{"label":"xxcbhi"}, "label":""}, "updated":{"label":"2021-07-13T20:26:01-07:00"}, "im:rating":{"label":"2"}, "im:version":{"label":"196.0"}, "id":{"label":"7573957313"}, "title":{"label":"Instagram"}, "content":{"label":"My main my spam are linked so if I log in to one it should log me into my other a long but for some reason it’s only letting me log in to my main not my spam", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id173632100"}, "name":{"label":"Humbug24"}, "label":""}, "updated":{"label":"2021-07-13T20:19:55-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573940824"}, "title":{"label":"My App Won’t Update"}, "content":{"label":"How is it that in July of 2021, Reels still isn’t available on my account? I wish Instagram would reply to the numerous requests for help on multiple platforms.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1273528658"}, "name":{"label":"Nessabarrettt"}, "label":""}, "updated":{"label":"2021-07-13T20:17:26-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7573934204"}, "title":{"label":"Dandelions"}, "content":{"label":"maybe it’s the way you say my name,\nmaybe it’s the way u play ur game\nBut it’s all good\nI’ve never met anybody like you\nBut it’s all good\nI’ve never dreamed of nobody like you\nAnd I heard of a love that only comes once in a life time\nAnd I’m pretty sure that you are that love of mine \n‘Cause I’m in a feild of dandelions \nwishing on everyone that you’d be mine \nMine \nAnd I see forever in your eyes\nI feel ok when I see you smile \nsmile \nWishing on dandelions all of the time\npraying to God that one day you’d be mine\nWishing on dandelions all of the time \nAll of the time \nI think that you are the one for me\n‘Cause it gets so hard to breathe \nWhen your looking at me\nI’ve never felt so alive and free\nI’ve never felt so happy\nAnd I’ve heard that love only comes once in a lifetime\nAnd I’m pretty sure that you are that love of mine \n‘Cause I’m in a feild of dandelions wishing on everyone that you’d be mine \nMine \nand I see forever in your eyes \nI feel ok when I see you smile\nDandelion , into the wind you go \nWon’t you let my darling know \ndandelions into the wind u go\nWon’t you let my darling know\nthat\nI’m in a feild of dandelions \nWishing on everyone that you’d be mine \nMine\nand I see forever in your eyes \nI feel ok when I see you smile\nSmile\nWishing on dandelions all of the time \nPraying to God that one day you’d be mine \nWishing on dandelions all of the time \nAll of the time\nI’m in a feild of dandelions \nwishing on everyone that you’d be mine \nMine", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id638164056"}, "name":{"label":"weezyduzit"}, "label":""}, "updated":{"label":"2021-07-13T20:05:32-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573902691"}, "title":{"label":"Truth/ reality"}, "content":{"label":"Way too many ads. Sucked since you took it of chronological posting . Works as a bot. Had two business pages taken down for no reason and never able to recover cause there’s no customer service. Lastly I am tired of pages being hacked.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id937081159"}, "name":{"label":"Clayslau"}, "label":""}, "updated":{"label":"2021-07-13T19:56:31-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7573879603"}, "title":{"label":"Awesome"}, "content":{"label":"Amazing lol", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id573032118"}, "name":{"label":"Mama Eggers"}, "label":""}, "updated":{"label":"2021-07-13T19:31:32-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573816299"}, "title":{"label":"Update Nightmare"}, "content":{"label":"I just update Instagram latest version and now I can’t get back in. Ever since this last Saturday. \nI’ve tried everything except delete it off my phone, because according to the description of “Delete “ you lose all files. This is twice I’ve had this happen to me and it’s quite frustrating.\nAnyone have another idea?\nBummed out…", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1277088165"}, "name":{"label":"nicknamebswtf"}, "label":""}, "updated":{"label":"2021-07-13T19:27:09-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7573804964"}, "title":{"label":"Bluegrass Dreams"}, "content":{"label":"IG is lit", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id623042127"}, "name":{"label":"PaQue preguntas"}, "label":""}, "updated":{"label":"2021-07-13T19:22:12-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7573792572"}, "title":{"label":"Need help"}, "content":{"label":"I have two accounts on my phone for IG. One account let’s me use Reels, but on the other one, it doesn’t even give me an option\n\nPlease help", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1145293269"}, "name":{"label":"TROLL🙂"}, "label":""}, "updated":{"label":"2021-07-13T19:09:52-07:00"}, "im:rating":{"label":"2"}, "im:version":{"label":"196.0"}, "id":{"label":"7573760536"}, "title":{"label":"Many things did not work"}, "content":{"label":"Personally many of the features didn't work  such as the \"music\" sticker, the log out, and the delete account.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id986154368"}, "name":{"label":"martinjayde"}, "label":""}, "updated":{"label":"2021-07-13T19:06:56-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7573752716"}, "title":{"label":"Jayde Martin"}, "content":{"label":"Love Instagram 🥰☺️🤟🏻", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id702941034"}, "name":{"label":"b chi c x h"}, "label":""}, "updated":{"label":"2021-07-13T19:02:00-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573740069"}, "title":{"label":"This account is trash"}, "content":{"label":"I just started Instagram and it give me a compromised", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1130292431"}, "name":{"label":"jfjfigjfjcjcjcjcjcjcci"}, "label":""}, "updated":{"label":"2021-07-13T18:49:34-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573707367"}, "title":{"label":"Instagram is glitching"}, "content":{"label":"My Instagram is having this really bad glitch and u guys really  need to fix it", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id164545979"}, "name":{"label":"yambaram"}, "label":""}, "updated":{"label":"2021-07-13T18:44:47-07:00"}, "im:rating":{"label":"2"}, "im:version":{"label":"196.0"}, "id":{"label":"7573694819"}, "title":{"label":"User support is non-existent"}, "content":{"label":"I love using the app to share and browse images.\nBut with zero customer support, if you have an in app issue there is simply no one to talk to. This is frustrating and unfortunate.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1189221740"}, "name":{"label":"CM_WINGS"}, "label":""}, "updated":{"label":"2021-07-13T18:43:31-07:00"}, "im:rating":{"label":"4"}, "im:version":{"label":"196.0"}, "id":{"label":"7573691432"}, "title":{"label":"Read it"}, "content":{"label":"Better before FB took over…. Stop tracking me", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id217637836"}, "name":{"label":"mligenzaa"}, "label":""}, "updated":{"label":"2021-07-13T18:40:20-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573682821"}, "title":{"label":"keeps getting worse"}, "content":{"label":"instagram worked perfectly fine for years. now since the shopping tab was introduced it keeps getting worse. there’s a group chat i message every day but in the dm a post feature i have to scroll down in the order gcs were created. it also says i have 9+ new messages and an unopened photo. i do not. and just today videos don’t play. it’s not a bad connection the audio plays but the picture does not. i tried uninstalling and reinstalling the app to no avail. it won’t let me log out of my account either.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id590683970"}, "name":{"label":"GlaceonCat8DRAWS"}, "label":""}, "updated":{"label":"2021-07-13T18:32:54-07:00"}, "im:rating":{"label":"3"}, "im:version":{"label":"196.0"}, "id":{"label":"7573663796"}, "title":{"label":"fix the story update GO BACK GO BACK"}, "content":{"label":"I don’t know what on this earth you just did with the story update but it’s BAD- PLEASE go back PLEASE I’m begging \nI keep accidentally saving stories and whatever it’s getting annoying\nFirst the layout change now this can you please stop thank you\nI don’t know if you ever take neurodivergent people into consideration but it’s hard for us to navigate a completely new layout when it’s been the same for so long.\nSeriously.\nanyways. thanks i guess.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1108516198"}, "name":{"label":"cf091066"}, "label":""}, "updated":{"label":"2021-07-13T18:20:52-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7573633108"}, "title":{"label":"Lo mejor"}, "content":{"label":"Excelente", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id593864213"}, "name":{"label":"GATA1981"}, "label":""}, "updated":{"label":"2021-07-13T18:17:32-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573624379"}, "title":{"label":"Trash app"}, "content":{"label":"I keep getting notifications for things that aren’t even there to view.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id198967733"}, "name":{"label":"Spangler Family USMC"}, "label":""}, "updated":{"label":"2021-07-13T18:15:14-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7573618437"}, "title":{"label":"Amazing"}, "content":{"label":"It is cool how u can hide ur page from people u don’t like", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id206155065"}, "name":{"label":"Linds7464"}, "label":""}, "updated":{"label":"2021-07-13T18:02:13-07:00"}, "im:rating":{"label":"2"}, "im:version":{"label":"196.0"}, "id":{"label":"7573584669"}, "title":{"label":"Can’t Share Stories"}, "content":{"label":"I love IG and use it for my business. But recently I can’t share stories from public accounts to my accounts. It’s super frustrating because I need this for the three accounts I manage. The ‘share to your story’ doesn’t show up. I’ve written the help desk 7 times. Please fix @thecottagemama @savannah_wilkes", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id577146225"}, "name":{"label":"c-water"}, "label":""}, "updated":{"label":"2021-07-13T17:50:31-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573555314"}, "title":{"label":"Ready to delete"}, "content":{"label":"Instagram was better before it decided that photos were not the priority and then started pushing suggested ads.  I will follow what I want and if I can’t see the accounts I want because of the “suggested ads” then I’ll just delete Instagram.   Stop “upgrading” because you are taking a million steps backwards and this app is becoming garbage.   I use to love Instagram now I can honestly do without it.  Go back to what made you.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1159442323"}, "name":{"label":"iraqqmemo"}, "label":""}, "updated":{"label":"2021-07-13T17:50:19-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573554832"}, "title":{"label":"My account locked"}, "content":{"label":"Hi my account locked by mistake told ig don’t respond", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id757080776"}, "name":{"label":"tyfbmk"}, "label":""}, "updated":{"label":"2021-07-13T17:50:06-07:00"}, "im:rating":{"label":"5"}, "im:version":{"label":"196.0"}, "id":{"label":"7573554334"}, "title":{"label":"Instagram fan since 2011"}, "content":{"label":"Luileett. 👍🏼", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1182344168"}, "name":{"label":"Villa956"}, "label":""}, "updated":{"label":"2021-07-13T17:42:59-07:00"}, "im:rating":{"label":"3"}, "im:version":{"label":"196.0"}, "id":{"label":"7573536779"}, "title":{"label":"Weird"}, "content":{"label":"I was texting people then it’ says something I shared my password but I never did!!! And when I downloaded the app again it still says it help me!!", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id1274108642"}, "name":{"label":"duhvdfgh"}, "label":""}, "updated":{"label":"2021-07-13T17:38:54-07:00"}, "im:rating":{"label":"1"}, "im:version":{"label":"196.0"}, "id":{"label":"7573526669"}, "title":{"label":"i dont have the update :("}, "content":{"label":"i had instagram for a long time now. when my other account was banned i made a new one and i still didnt get the update with the messenger \nconnected to it. please help me :(.", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}},
{"author":{"uri":{"label":"https://itunes.apple.com/us/reviews/id463868072"}, "name":{"label":"ChampDabber"}, "label":""}, "updated":{"label":"2021-07-13T17:27:15-07:00"}, "im:rating":{"label":"3"}, "im:version":{"label":"196.0"}, "id":{"label":"7573499428"}, "title":{"label":"I DON’T HAVE THE HIDE LIKES FEATURE"}, "content":{"label":"My app is up to date but why don’t I still have the “hide likes” feature??", "attributes":{"type":"text"}}, "link":{"attributes":{"rel":"related", "href":"https://itunes.apple.com/us/review?id=389801252&type=Purple%20Software"}}, "im:voteSum":{"label":"0"}, "im:contentType":{"attributes":{"term":"Application", "label":"Application"}}, "im:voteCount":{"label":"0"}}], "updated":{"label":"2021-07-15T08:37:12-07:00"}, "rights":{"label":"Copyright 2008 Apple Inc."}, "title":{"label":"iTunes Store: Customer Reviews"}, "icon":{"label":"http://itunes.apple.com/favicon.ico"}, "link":[
{"attributes":{"rel":"alternate", "type":"text/html", "href":"https://music.apple.com/WebObjects/MZStore.woa/wa/viewGrouping?cc=us&id=1"}},
{"attributes":{"rel":"self", "href":"https://mzstoreservices-int-st.itunes.apple.com/us/rss/customerreviews/id=389801252/mostrecent/json"}},
{"attributes":{"rel":"first", "href":"https://itunes.apple.com/us/rss/customerreviews/page=1/id=389801252/sortby=mostrecent/xml?urlDesc=/customerreviews/id=389801252/mostrecent/json"}},
{"attributes":{"rel":"last", "href":"https://itunes.apple.com/us/rss/customerreviews/page=10/id=389801252/sortby=mostrecent/xml?urlDesc=/customerreviews/id=389801252/mostrecent/json"}},
{"attributes":{"rel":"previous", "href":"https://itunes.apple.com/us/rss/customerreviews/page=1/id=389801252/sortby=mostrecent/xml?urlDesc=/customerreviews/id=389801252/mostrecent/json"}},
{"attributes":{"rel":"next", "href":"https://itunes.apple.com/us/rss/customerreviews/page=2/id=389801252/sortby=mostrecent/xml?urlDesc=/customerreviews/id=389801252/mostrecent/json"}}], "id":{"label":"https://mzstoreservices-int-st.itunes.apple.com/us/rss/customerreviews/id=389801252/mostrecent/json"}}}